spring.application.name=desafio-itau
#Definição do tempo limite
app.estatisticas.tempo-limite=60
#http://localhost:8080/actuator ou http://localhost:8080/actuator/health
management.endpoints.web.exposure.include=health
#Para mostrar mais detalhes da saúde da aplicação
management.endpoint.health.show-details=always
#http://localhost:8080/swagger-ui/index.html para acessar a documentação do swagger
springdoc.show-actuator=true